name: Monthly Automation

on:
  schedule:
    - cron: '0 8 8 * *' # runs at 8:00 UTC (10:00 CET time) on the 8th of each month
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run script
        env:
          AMAZON_SELLER_EMAIL: ${{ secrets.AMAZON_SELLER_EMAIL }}
          AMAZON_SELLER_PASSWORD: ${{ secrets.AMAZON_SELLER_PASSWORD }}
          AMAZON_SELLER_TOTP_SECRET: ${{ secrets.AMAZON_SELLER_TOTP_SECRET }}

          # Bol.com API credentials for 4 accounts
          BOL_USERNAME_1: ${{ secrets.BOL_USERNAME_1 }}
          BOL_CLIENT_ID_1: ${{ secrets.BOL_CLIENT_ID_1 }}
          BOL_API_SECRET_1: ${{ secrets.BOL_API_SECRET_1 }}

          BOL_USERNAME_2: ${{ secrets.BOL_USERNAME_2 }}
          BOL_CLIENT_ID_2: ${{ secrets.BOL_CLIENT_ID_2 }}
          BOL_API_SECRET_2: ${{ secrets.BOL_API_SECRET_2 }}

          BOL_USERNAME_3: ${{ secrets.BOL_USERNAME_3 }}
          BOL_CLIENT_ID_3: ${{ secrets.BOL_CLIENT_ID_3 }}
          BOL_API_SECRET_3: ${{ secrets.BOL_API_SECRET_3 }}

          BOL_USERNAME_4: ${{ secrets.BOL_USERNAME_4 }}
          BOL_CLIENT_ID_4: ${{ secrets.BOL_CLIENT_ID_4 }}
          BOL_API_SECRET_4: ${{ secrets.BOL_API_SECRET_4 }}

          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: python main.py
